name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Composer Install
      run: composer install
    
    - name: PHPUnit Testing
      run: ./vendor/bin/phpunit ./tests --colors

    - name: PhpStan Code Analyzing
      run: ./vendor/bin/phpstan analyze ./index.php --level 5
    
    - name: Custom Error Log
      run: ./vendor/bin/phpstan analyze ./customTests/manuel-test.php